id: P11154215
initial_creation_type: input
source_metadata:
  title: Mind Training (Lojong)
  language: fr
  description: 'Texts on so-called mind training (blo sbyong), the system of practical
    instructions for developing the compassion and wisdom of bodhicitta:'
  volume:
    523a6a266c6c4211a134c609bd50be6d:
      title: Seven Points of Training the Mind According to the Great Vehicle
      parent: Seven Points of Mind Training
    5a639c56644d4d62afbc4c81134f6b14:
      title: Commentary on the Seven Points
      parent: Seven Points of Mind Training
    292c185b0b7d4dcfaf64b76f510f71cb:
      title: Notes on the Seven Points of Mind Training
      parent: Seven Points of Mind Training
    b44ebe8868d844d9b2f9d48c77fd65de:
      title: Ambrosia for the Mind
      parent: Seven Points of Mind Training
    4d2410007abb417c8ff35f2d6599fd56:
      title: Eight Verses of Training the Mind
      parent: Eight Verses of Training the Mind
    a362170df8fa4313bc76813e3ea2f93a:
      title: The Thirty-Seven Practices of All the Bodhisattvas
      parent: Thirty-Seven Practices
    9667b287e0e3480f89223bd205b38cb3:
      title: 'The Blissful Path to the Ocean of Bodhichitta: A Brief Prayer of Aspiration
        for Mind Training'
      parent: Aspiration Prayers
    81b72a6bc799485b88f385deb7e7b65a:
      title: 'The Excellent Path to Enlightenment: An Aspiration Towards the Mahāyāna
        Mind Training'
      parent: Aspiration Prayers
    a4386b4872234e4ca1f36d8a8214b7a1:
      title: 'The Finest Jewel: An Aspiration Prayer of Mahāyāna Mind Training'
      parent: Aspiration Prayers
    c46f5b8db5f24ee8b788f43ccc3b2040:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspiration Prayers
    fdbf8970bc68440b98d961ef344727c6:
      title: The Bodhisattva’s Garland of Jewels
      parent: Lojong (general)
    048595be2f36491795b53f5ea74b97c4:
      title: Turning Suffering & Happiness Into Enlightenment
      parent: Lojong (general)
    8210685bc5f54ea0b5fff46960622f05:
      title: The Sayings of Geshe Langri Tangpa
      parent: Lojong (general)
    28025865188a4023bceb35f41286a662:
      title: How to Transform Sickness and Other Circumstances
      parent: Lojong (general)
    1639d4e90e4b46dd86005edc6af4fa38:
      title: Thirty Pieces of Heart Advice
      parent: Lojong (general)
    b447458ee6ac4840a9ffe7b21c6986ac:
      title: Three Principal Aspects of the Path
      parent: Lojong (general)
created_at: '2022-03-01T04:44:49.390490'
last_modified_at: '2022-03-01T04:44:49.390493'
